In [2]:

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile, Aer, IBMQ
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from ibm_quantum_widgets import *
from qiskit.providers.aer import QasmSimulator

# Loading your IBM Quantum account(s)
provider = IBMQ.load_account()

ibmqfactory.load_account:WARNING:2021-11-10 05:15:09,503: Credentials are already in use. The existing account in the session will be replaced.


In [3]:
import numpy as np
from scipy.linalg import *

In [6]:
A = np.array([[9, 14], [10, 27], [11, 18]])
A

array([[ 9, 14],
       [10, 27],
       [11, 18]])

In [7]:
U, sigma, VT = svd(A)

In [8]:
U

array([[-0.42160323,  0.51024606, -0.74959968],
       [-0.73160231, -0.67980219, -0.05125468],
       [-0.535732  ,  0.52679972,  0.65990399]])

In [9]:
sigma

array([39.18073937,  3.98367447])

In [10]:
VT

array([[-0.43397609, -0.90092439],
       [ 0.90092439, -0.43397609]])

In [15]:
#reconstruct A from SVD
Ligma = np.zeros((A.shape[0], A.shape[1]))
Ligma[:A.shape[1], :A.shape[1]] = np.diag(sigma)
A_recon = U.dot(Ligma.dot(VT))
A_recon

array([[ 9., 14.],
       [10., 27.],
       [11., 18.]])

In [16]:
!pip install pyqentangle

     |████████████████████████████████| 46 kB 36 kB/s s eta 0:00:01
     |████████████████████████████████| 364 kB 28.3 MB/s eta 0:00:01
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Created wheel for pyqentangle: filename=pyqentangle-3.1.10-cp38-cp38-linux_x86_64.whl size=109809 sha256=e7cd45b2feffc927606f114bdc0b18d6723b7b41bb16b8c2bdd3cf0d9df39dae
  Stored in directory: /home/jovyan/.cache/pip/wheels/29/ba/bc/ef02ac32f4e3f3aa35559c7b570c8b5a830710e378af1bbc77
Successfully built pyqentangle


In [17]:
from pyqentangle import *

In [19]:
tensor = np.array([[0., sigma[0]], [sigma[1], 0.]])
tensor

array([[ 0.        , 39.18073937],
       [ 3.98367447,  0.        ]])

In [20]:
schmidt_decomposition(tensor)

[(39.180739371917625,
  array([-1.00000000e+00,  2.22044605e-16]),
  array([-0., -1.])),
 (3.9836744683601215, array([ 0., -1.]), array([-1., -0.]))]

### The only question is how to SVD and Schmidt Decomposition fit together?
> check notes in Project Notebook

In [22]:
!pip install colorama
from colorama import Style, Fore

  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)


In [25]:
print(Style.BRIGHT + Fore.RED + "Singular Value Decomposition using scipy.linalg.svd\n")
print(Style.BRIGHT + Fore.YELLOW + "Matrix", A)
print()
print(Style.BRIGHT + Fore.BLUE + "U is ", U)
print()
print(Style.BRIGHT + Fore.BLUE + "Σ is", sigma)
print()
print(Style.BRIGHT + Fore.BLUE + "V Transpose is", VT)

Singular Value Decomposition using scipy.linalg.svd

Matrix [[ 9 14]
 [10 27]
 [11 18]]

U is  [[-0.42160323  0.51024606 -0.74959968]
 [-0.73160231 -0.67980219 -0.05125468]
 [-0.535732    0.52679972  0.65990399]]

Σ is [39.18073937  3.98367447]

V Transpose is [[-0.43397609 -0.90092439]
 [ 0.90092439 -0.43397609]]


In [27]:
print(Style.BRIGHT + Fore.RED + "Schmidt Decomposition using pyqentangle.schmidt_decomposition\n")
print(Style.BRIGHT + Fore.YELLOW, schmidt_decomposition(tensor))

Schmidt Decomposition using pyqentangle.schmidt_decomposition

 [(39.180739371917625, array([-1.00000000e+00,  2.22044605e-16]), array([-0., -1.])), (3.9836744683601215, array([ 0., -1.]), array([-1., -0.]))]
